merge dz2 to master
3RUN/KochkarovAndroidPvt pull request #3
Opened 2019-06-19 00:13 UTC by 3RUN

2019-06-22 13:00 UTC, tim-teacher requested changes

2019-06-22 13:00 UTC, tim-teacher commented on app/src/main/java/by/itacademy/pvt/dz2/Dz2Activity.kt
> +                val image = findViewById<View>(R.id.imageLoaderView)
findViewById внутри клика, будет на каждый клик вызываться

2019-06-22 13:00 UTC, tim-teacher commented on app/src/main/java/by/itacademy/pvt/dz2/Dz2Activity.kt
> +    inner class CircleTransform : Transformation {
вынесете в отдельный класс, не нужно мешать в одном классе разную функциональность, внутринний класс не очень вариант.

2019-06-22 13:00 UTC, tim-teacher commented on app/src/main/java/by/itacademy/pvt/menu/MenuActivity.kt
> +        findViewById<View>(R.id.dzButtonId)
findViewById() внутриклика - проверьте весь код на это

2019-06-22 13:24 UTC, 3RUN commented
Внес все изменения. Спасибо.

2019-06-22 14:05 UTC, JerryMann approved these changes

2019-06-23 08:46 UTC, tim-teacher requested changes

2019-06-23 08:46 UTC, jushlwest commented on app/src/main/java/by/itacademy/pvt/dz2/Dz2Activity.kt
> +                val editTextView = findViewById<EditText>(R.id.urlEditText)
findViewById по прежнему внутри клика

2019-06-23 08:54 UTC, 3RUN commented on app/src/main/java/by/itacademy/pvt/dz2/Dz2Activity.kt
> +                val editTextView = findViewById<EditText>(R.id.urlEditText)
исправил, спасибо

2019-06-23 11:27 UTC, tim-teacher approved these changes

2019-06-23 11:51 UTC, merged